function Indiancomp()
{
    return(
        <div>
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" /><style dangerouslySetInnerHTML={{__html: " " }} />
        <div bgcolor="#DEEAF6" lang="EN-IN" link="blue" vlink="#954F72" style={{wordWrap: 'break-word'}}>
          <div className="m_WordSection1">
            <p className="MsoNormal"><b><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%', fontFamily: '"Cambria",serif'}}>INDIAN CUISINE:<u /><u /></span></b></p>
            <p className="MsoNormal"><u><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>INTRODUCTION:<u /><u /></span></u></p>
            <p className="MsoNormal"><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>Indian
                cuisine consists of a variety of regional and traditional cuisines native
                to the </span><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Indian_subcontinent&source=gmail-html&ust=1638993938809000&usg=AOvVaw1S4YXioYPSDLv09HohrP6z" title="Indian subcontinent" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', color: 'black', background: 'white', textDecoration: 'none'}}>Indian subcontinent</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>. Given the
                diversity in soil, climate, culture, ethnic groups, and occupations, these
                cuisines vary substantially and use locally available </span><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Spice&source=gmail-html&ust=1638993938809000&usg=AOvVaw2zWaG2dq_EWZJMxxLor6xx" title="Spice" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>spices</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>, </span></b><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Herb&source=gmail-html&ust=1638993938809000&usg=AOvVaw3MeifYL78fbkfKvPT2Enfc" title="Herb" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>herbs</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>, </span></b><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Vegetable&source=gmail-html&ust=1638993938809000&usg=AOvVaw2TK9vUcWhRSOCjw7HWf9JM" title="Vegetable" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>veget<wbr />ables</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>, and </span></b><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Fruit&source=gmail-html&ust=1638993938809000&usg=AOvVaw3p4mGVTeDyZAoSZWs_C814" title="Fruit" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>fruits</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>.</span></b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}><u /><u /></span></p>
            <p className="MsoNormal"><u><span style={{fontFamily: '"Cambria",serif'}}>STAPLE FOOD:<u /><u /></span></u></p>
            <p className="MsoNormal"><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Staple_food&source=gmail-html&ust=1638993938809000&usg=AOvVaw3Cy3wKzJKTpJqYhV6W4_ap" title="Staple food" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', color: 'black', background: 'white', textDecoration: 'none'}}>Staple foods</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}> of Indian cuisine include, <u /><u /></span></p>
            <p className="m_MsoListParagraphCxSpFirst"><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Pearl_millet&source=gmail-html&ust=1638993938809000&usg=AOvVaw0IFOq7C-O0DW4SJeKLL1S9" title="Pearl millet" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>Pearl millet</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> (<span className="m_SpellE"><i>bājra</i></span>) <u /><u /></span></b></p>
            <p className="m_MsoListParagraphCxSpMiddle"><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Rice&source=gmail-html&ust=1638993938809000&usg=AOvVaw0_XN2p6rdCHgq_VMO_Y-Kg" title="Rice" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>Rice</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> <u /><u /></span></b></p>
            <p className="m_MsoListParagraphCxSpLast"><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>W</span></b><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Whole-wheat_flour&source=gmail-html&ust=1638993938809000&usg=AOvVaw0CEpnVudxDO9Cz-veFpBaK" title="Whole-wheat flour" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>hole-wheat flour</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> (<span className="m_SpellE"><i>aṭṭa</i></span>)</span></b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}> <u /><u /></span></p>
            <p className="MsoNormal"><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>A variety of </span><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Lentil&source=gmail-html&ust=1638993938809000&usg=AOvVaw1RPceKzkjk8F_m6Nbbh88Y" title="Lentil" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', color: 'black', background: 'white', textDecoration: 'none'}}>lentils</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}> such as, <u /><u /></span></p>
            <p className="m_MsoListParagraphCxSpFirst"><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><i><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>masoor</span></i></b><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> (most often red </span></b><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Lentil&source=gmail-html&ust=1638993938809000&usg=AOvVaw1RPceKzkjk8F_m6Nbbh88Y" title="Lentil" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>lentils</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>), <u /><u /></span></b></p>
            <p className="m_MsoListParagraphCxSpMiddle"><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span className="m_SpellE"><b><i><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>tuer</span></i></b></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> (</span></b><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Pigeon_pea&source=gmail-html&ust=1638993938809000&usg=AOvVaw2pheJQgmKPdJMlxo9yUn0J" title="Pigeon pea" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>pigeon peas</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>),<u /><u /></span></b></p>
            <p className="m_MsoListParagraphCxSpMiddle"><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> </span></b><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Urad_(bean)&source=gmail-html&ust=1638993938809000&usg=AOvVaw2kg4hCw9rG3hEWnWv7r-vc" title="Urad (bean)" target="_blank" rel="noreferrer"><b><i><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>urad</span></i></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> (black gram)<u /><u /></span></b></p>
            <p className="m_MsoListParagraphCxSpMiddle"><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><i><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>moong</span></i></b><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> (</span></b><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Mung_bean&source=gmail-html&ust=1638993938809000&usg=AOvVaw1-nvnX3CB-HtR2bufLdt1r" title="Mung bean" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>mung beans</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>). <u /><u /></span></b></p>
            <p className="m_MsoListParagraphCxSpMiddle"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}><u /> <u /></span></b></p>
            <p className="m_MsoListParagraphCxSpMiddle" style={{marginLeft: '54.0pt'}}><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Wingdings', color: 'black'}}><span>Ø<span style={{font: '7.0pt "Times New Roman"'}}></span></span></span><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>Lentils may be used whole, </span><span className="m_SpellE"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>dehusked</span></b></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> <span className="m_SpellE"><i>dhuli</i></span><i>
                    moong</i> or <span className="m_SpellE"><i>dhuli</i></span><i> urad</i></span></b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>or split. <u /><u /></span></p>
            <p className="m_MsoListParagraphCxSpMiddle" style={{marginLeft: '54.0pt'}}><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Wingdings', color: 'black'}}><span>Ø<span style={{font: '7.0pt "Times New Roman"'}}></span></span></span><u /><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>Split lentils,
                  or <span className="m_GramE"><i>dal </i><span style={{color: 'black', fontWeight: 'normal'}}>,</span></span></span></b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}> are used extensively. <u /><u /></span></p>
            <p className="m_MsoListParagraphCxSpMiddle"><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}><u /> <u /></span></p>
            <p className="m_MsoListParagraphCxSpMiddle"><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>Some </span><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Pulse_(legume)&source=gmail-html&ust=1638993938809000&usg=AOvVaw3BNm51JrBiFFi3m_GxKDJn" title="Pulse (legume)" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', color: 'black', background: 'white', textDecoration: 'none'}}>pulses</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}> such as,<u /><u /></span></p>
            <p className="m_MsoListParagraphCxSpMiddle" style={{marginLeft: '72.0pt'}}><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span className="m_SpellE"><b><i><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>channa</span></i></b></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> or <span className="m_SpellE"><i>cholae</i></span></span></b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> </span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>(</span><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Chickpea&source=gmail-html&ust=1638993938810000&usg=AOvVaw17BUi6Bqb_2aTa-SQewwOR" title="Chickpea" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', color: 'black', background: 'white', textDecoration: 'none'}}>chickpeas</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>)<u /><u /></span></p>
            <p className="m_MsoListParagraphCxSpMiddle" style={{marginLeft: '72.0pt'}}><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Rajma&source=gmail-html&ust=1638993938810000&usg=AOvVaw27B7rkxUQ9CZGhYtW5bZgG" title="Rajma" target="_blank" rel="noreferrer"><b><i><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>rajma</span></i></b></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}> (</span><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Kidney_bean&source=gmail-html&ust=1638993938810000&usg=AOvVaw1OtDDdTI40R-7BYTtD_l7c" title="Kidney bean" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', color: 'black', background: 'white', textDecoration: 'none'}}>kidney beans</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>)<u /><u /></span></p>
            <p className="m_MsoListParagraphCxSpMiddle" style={{marginLeft: '72.0pt'}}><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span className="m_SpellE"><b><i><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>lobiya</span></i></b></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> </span></b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>(</span><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Black-eyed_pea&source=gmail-html&ust=1638993938810000&usg=AOvVaw3dERivE7zgj-dsQk4R6Y_f" title="Black-eyed pea" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', color: 'black', background: 'white', textDecoration: 'none'}}>black-eyed peas</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>) are very common especially in the
                northern regions. <u /><u /></span></p>
            <p className="m_MsoListParagraphCxSpLast" style={{marginLeft: '72.0pt'}}><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><i><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>Channa</span></i></b><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> </span></b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>and </span><b><i><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}>moong</span></i></b><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> </span></b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>are also processed into flour (<span className="m_SpellE"><i><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Gram_flour&source=gmail-html&ust=1638993938810000&usg=AOvVaw0GIxXbflMP9go28ZziGHu7" title="Gram flour" target="_blank" rel="noreferrer"><span style={{color: 'black', textDecoration: 'none'}}>besan</span></a></i></span>).<u /><u /></span></p>
            <p className="MsoNormal"><u><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>OILs USED IN INDIAN CUISINE:<u /><u /></span></u></p>
            <p className="MsoNormal"><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>Many Indian dishes are cooked in <u /><u /></span></p>
            <p className="m_MsoListParagraphCxSpFirst"><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Vegetable_oil&source=gmail-html&ust=1638993938810000&usg=AOvVaw2gbzwtYYKX5oKEBy1FuTuF" title="Vegetable oil" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>Vegetable oil</span></b></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}><u /><u /></span></p>
            <p className="m_MsoListParagraphCxSpMiddle"><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Peanut_oil&source=gmail-html&ust=1638993938810000&usg=AOvVaw29RJyTNINs0x8HzLGUCPmw" title="Peanut oil" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>Peanut oil</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#8496b0', background: 'white'}}> </span></b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}><u /><u /></span></p>
            <p className="m_MsoListParagraphCxSpMiddle"><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Mustard_oil&source=gmail-html&ust=1638993938810000&usg=AOvVaw15-zn8K78GthlnMoDAW2au" title="Mustard oil" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>Mustard oil</span></b></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}><u /><u /></span></p>
            <p className="m_MsoListParagraphCxSpMiddle"><u /><span style={{fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><span style={{fontFamily: '"Cambria",serif', color: '#8496b0'}}><span> </span></span></b><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Coconut_oil&source=gmail-html&ust=1638993938810000&usg=AOvVaw25wjMLuy2Fm2jroJSzD-wa" title="Coconut oil" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>Coconut oil</span></b></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}> (Kerala
                food &amp; Tamil Nadu food).</span><span style={{fontFamily: '"Cambria",serif', color: 'black'}}> <u /><u /></span></p>
            <p className="m_MsoListParagraphCxSpLast"><u /><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Sesame_oil&source=gmail-html&ust=1638993938810000&usg=AOvVaw2EGvmpiQX6gDVKesIuvDWw" title="Sesame oil" target="_blank" rel="noreferrer"><b><i><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}>Gingelly</span></i></b><b><span style={{fontSize: '10.5pt', lineHeight: '115%', color: '#8496b0', background: 'white', textDecoration: 'none'}}> (sesame) oil</span></b></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}> is
                common in the south since it imparts a fragrant, nutty aroma. <u /><u /></span></p>
            <p className="MsoNormal"><span className="m_GramE"><u><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%', fontFamily: '"Cambria",serif'}}>SPICES :</span></u></span><u><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%', fontFamily: '"Cambria",serif'}}><u /><u /></span></u></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '0cm', background: 'white'}}><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>The most important and frequently used spices and
                flavourings in Indian cuisine are whole or powdered <u /><u /></span></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Chili_pepper&source=gmail-html&ust=1638993938810000&usg=AOvVaw2p4dQD0eqkqKEcAhgCmodq" title="Chili pepper" target="_blank" rel="noreferrer"><span className="m_SpellE"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>Chillipepper</span></b></span></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> (<span className="m_SpellE"><i>mirch</i></span>)<u /><u /></span></b></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Brassica_nigra&source=gmail-html&ust=1638993938810000&usg=AOvVaw1ElkcbmoRSU0hKsn-FDg8v" title="Brassica nigra" target="_blank" rel="noreferrer"><span className="m_SpellE"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>blackmustard</span></b></span></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> seed (<span className="m_SpellE"><i>sarso</i></span>)<u /><u /></span></b></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Cardamom&source=gmail-html&ust=1638993938810000&usg=AOvVaw0fcL8awgWxhEVu5l37sM58" title="Cardamom" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>cardamom</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> (<span className="m_SpellE"><i>elaichi</i></span>)<u /><u /></span></b></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Cumin&source=gmail-html&ust=1638993938810000&usg=AOvVaw3auhkyjRs4H0LQOzI49FM5" title="Cumin" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>cumin</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> (<i>jeera</i>)<u /><u /></span></b></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Turmeric&source=gmail-html&ust=1638993938810000&usg=AOvVaw2JkKTn6P6i4wWKk87A6Fr0" title="Turmeric" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>turmeric</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> (<span className="m_SpellE"><i>haldi</i></span>)<u /><u /></span></b></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Asafoetida&source=gmail-html&ust=1638993938810000&usg=AOvVaw0XDC5jvWbVAl_Uqr-DzQIK" title="Asafoetida" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>asafoetida</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> (<span className="m_SpellE"><i>hing</i></span>)<u /><u /></span></b></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Ginger&source=gmail-html&ust=1638993938810000&usg=AOvVaw1Tzk2usBb4-kVqBj9211PW" title="Ginger" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>ginger</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> (<span className="m_SpellE"><i>adrak</i></span>)<u /><u /></span></b></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Coriander&source=gmail-html&ust=1638993938810000&usg=AOvVaw3QcFqO99AujkMj6ufSMO63" title="Coriander" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>coriander</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> (<i>dhania</i>)<u /><u /></span></b></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Garlic&source=gmail-html&ust=1638993938810000&usg=AOvVaw2vBcQIeS2Fm6rXl5W5qyoo" title="Garlic" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>garlic</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> (<span className="m_SpellE"><i>lasoon</i></span>). </span></b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}><u /><u /></span></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}><u /> <u /></span></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Wingdings', color: 'black'}}><span>Ø<span style={{font: '7.0pt "Times New Roman"'}}> 
                  </span></span></span><u /><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}>One popular </span></b><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Spice_mix&source=gmail-html&ust=1638993938810000&usg=AOvVaw3rm-V0KRPgEduSdhHTHS2H" title="Spice mix" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>spice mix</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> is </span></b><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Garam_masala&source=gmail-html&ust=1638993938810000&usg=AOvVaw0Eb6d6VIRuLDVbtSm8OUaL" title="Garam masala" target="_blank" rel="noreferrer"><b><i><span style={{fontSize: '10.5pt', color: '#8496b0'}}>garam masala</span></i></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}>, a powder that typically includes seven dried spices in a particular ratio,
                  including </span></b><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Cardamom&source=gmail-html&ust=1638993938810000&usg=AOvVaw0fcL8awgWxhEVu5l37sM58" title="Cardamom" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>black cardamom</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}>, </span></b><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Cinnamon&source=gmail-html&ust=1638993938810000&usg=AOvVaw3UfCHhIatUfphmHVGTuNaD" title="Cinnamon" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>cinnamon</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> (<span className="m_SpellE"><i>dalchini</i></span>),<wbr /> </span></b><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Clove&source=gmail-html&ust=1638993938810000&usg=AOvVaw0-PxP391B4K7gqFC21zMk2" title="Clove" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>clove</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> (<span className="m_SpellE"><i>laung</i></span><i>),</i> cumin (jeera),
                  black peppercorns, coriander seeds and </span></b><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Illicium_verum&source=gmail-html&ust=1638993938810000&usg=AOvVaw1L_LJiV0p_NRZY5OJUU4gB" title="Illicium verum" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>anise star</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}>.</span></b><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}><u /><u /></span></b></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '0cm', background: 'white'}}><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}><u /> <u /></span></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Wingdings', color: 'black'}}><span>Ø<span style={{font: '7.0pt "Times New Roman"'}}></span></span></span><u /><span className="m_SpellE"><b><i><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}>Goda</span></i></b></span><b><i><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> <span className="m_GramE">masala<span style={{color: 'black', fontWeight: 'normal', fontStyle: 'normal'}}>, <span> </span>sweet</span></span></span></i></b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>, spice mix
                popular in </span><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Maharashtra&source=gmail-html&ust=1638993938810000&usg=AOvVaw2f2UYM7_DstU7vMu7r7E3-" title="Maharashtra" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', color: 'black'}}>Maharashtra</span></a></span><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>. <u /><u /></span></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '0cm', background: 'white'}}><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>Some leaves commonly used for flavouring include, <u /><u /></span></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Bay_leaf&source=gmail-html&ust=1638993938810000&usg=AOvVaw0G63eTQotFsNrJOJ02gEUE" title="Bay leaf" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>Bay leaves</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> (<span className="m_SpellE"><i><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Cinnamomum_tamala&source=gmail-html&ust=1638993938810000&usg=AOvVaw3YRNXKNV_ppIllnmhP-Fw5" title="Cinnamomum tamala" target="_blank" rel="noreferrer"><span style={{color: '#8496b0'}}>tejpat</span></a></i></span>)<u /><u /></span></b></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> </span></b><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Coriander&source=gmail-html&ust=1638993938810000&usg=AOvVaw3QcFqO99AujkMj6ufSMO63" title="Coriander" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>Coriander</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> leaves<u /><u /></span></b></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Fenugreek&source=gmail-html&ust=1638993938810000&usg=AOvVaw2jSCJQYTMiiO7f45XCaGLL" title="Fenugreek" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>Fenugreek</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> (<span className="m_SpellE"><i><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Methi&source=gmail-html&ust=1638993938810000&usg=AOvVaw1VIFItoKiZrgf-U3i7LPue" title="Methi" target="_blank" rel="noreferrer"><span style={{color: '#8496b0'}}>methi</span></a></i></span>)
                  leaves<u /><u /></span></b></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Mentha&source=gmail-html&ust=1638993938810000&usg=AOvVaw10nNatnyO2zuLvhWmloBMb" title="Mentha" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', color: '#8496b0'}}>Mint</span></b></a></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> leaves. </span></b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}><u /><u /></span></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '0cm', background: 'white'}}><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>The use of </span><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Curry_tree&source=gmail-html&ust=1638993938810000&usg=AOvVaw1VyyzI34RruWpclkD1Sfo3" title="Curry tree" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', color: 'black'}}>curry</span></a></span><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}> leaves
                and roots for flavouring is typical of </span><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Gujarati_cuisine&source=gmail-html&ust=1638993938810000&usg=AOvVaw3zgjpD9DWbs5fqqUrZ8usi" title="Gujarati cuisine" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', color: 'black'}}>Gujarati</span></a></span><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}> and </span><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/South_Indian_cuisine&source=gmail-html&ust=1638993938810000&usg=AOvVaw3pRphfDbzAOmUf8ueEQ2M4" title="South Indian cuisine" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', color: 'black'}}>South
                    Indian cuisine</span></a></span><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>.<u /><u /></span></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '38.25pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Wingdings', color: 'black'}}><span>Ø<span style={{font: '7.0pt "Times New Roman"'}}></span></span></span><u /><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>Sweet dishes
                are often seasoned with,<u /><u /></span></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '56.25pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}>Cardamom<u /><u /></span></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '56.25pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Saffron&source=gmail-html&ust=1638993938810000&usg=AOvVaw0I7H_VoQ7oLUKwUVZ2hCvD" title="Saffron" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', color: '#8496b0'}}>Saffron</span></a></span><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}><u /><u /></span></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '56.25pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Nutmeg&source=gmail-html&ust=1638993938811000&usg=AOvVaw2w0aUQ2uUcGlfnKzQS1Wa1" title="Nutmeg" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', color: '#8496b0'}}>Nutmeg</span></a></span><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}><u /><u /></span></p>
            <p style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '56.25pt', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#8496b0'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{fontFamily: '"Cambria",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Rose&source=gmail-html&ust=1638993938811000&usg=AOvVaw2T_oRbMFx62Ci8dqcy5glu" title="Rose" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', color: '#8496b0'}}>Rose</span></a></span><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#8496b0'}}> petal essences</span><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>.<u><u /><u /></u></span></p>
            <p className="MsoNormal"><u><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%'}}><u /><span style={{textDecoration: 'none'}}> </span><u /></span></u></p>
            <p className="MsoNormal"><b><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%'}}><u /> <u /></span></b></p>
            <p className="MsoNormal"><b><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%'}}><u /> <u /></span></b></p>
            <p className="MsoNormal"><b><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%'}}><u /> <u /></span></b></p>
            <p className="MsoNormal"><b><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%'}}><u /> <u /></span></b></p>
            <p className="MsoNormal"><b><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%'}}><u /> <u /></span></b></p>
            <p className="MsoNormal"><b><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%'}}><u /> <u /></span></b></p>
            <p className="MsoNormal"><b><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%'}}><u /> <u /></span></b></p>
            <p className="MsoNormal"><b><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%'}}><u /> <u /></span></b></p>
            <p className="MsoNormal"><u /> <u /></p>
          </div>
        </div>
      </div>
    );
}
export default Indiancomp