function IndoComp()
{
    return(
        <div>
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" /><style dangerouslySetInnerHTML={{__html: "p.m_MsoNormal,li.m_MsoNormal,div.m_MsoNormal{margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:11.0pt;font-family:\"Calibri\",sans-serif}span.m_SpellE{}.m_MsoChpDefault{font-family:\"Calibri\",sans-serif}.m_MsoPapDefault{margin-bottom:8.0pt;line-height:107%}@page WordSection1{margin:72.0pt 72.0pt 72.0pt 72.0pt}div.m_WordSection1{}ol{margin-bottom:0cm}ul{margin-bottom:0cm}" }} />
        <div bgcolor="#EDDFDA" lang="EN-IN" style={{wordWrap: 'break-word'}}>
          <div className="m_WordSection1">
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><b><u><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%', fontFamily: '"Cambria",serif'}}>INDONESIAN CUISINE<u /><u /></span></u></b></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>INTRODUCTION<u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>Indonesian cuisine often demonstrates
                complex flavour, acquired from certain ingredients and <span className="m_SpellE">bumbu</span>
                spices mixture. Indonesian dishes have rich flavours; most often described as <span className="m_SpellE">savory</span>, hot and spicy, and also combination of basic tastes
                such as sweet, salty, sour and bitter. Most Indonesians favour hot and spicy
                food, thus sambal, Indonesian hot and spicy chili sauce with various optional
                ingredients, notably shrimp paste, shallots, and others, is a staple condiment
                at all Indonesian tables. Seven main Indonesian cooking methods are frying,
                grilling, roasting, dry roasting, sautéing, boiling and steaming.<u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><u><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>STAPLE FOOD</span></u><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>:<u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>Indonesian food staples are mainly </span><span style={{lineHeight: '115%'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Rice&source=gmail-html&ust=1638995755878000&usg=AOvVaw2WqjBm0F3rhwk1Fq-jkOlK" title="Rice" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#548dd4', background: 'white', textDecoration: 'none'}}>rice</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#548dd4', background: 'white'}}>, </span></b><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#548dd4'}}>wheat, yam, sweet potato, potato, breadfruit and
                  jackfruit.</span></b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif'}}><u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><u><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%', fontFamily: '"Cambria",serif'}}>VEGETABLES USED IN CHINESE CUISINE:<u /><u /></span></u></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>Apart from vegetables that can be
                commonly seen, some unique </span><span style={{lineHeight: '115%'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Vegetables&source=gmail-html&ust=1638995755878000&usg=AOvVaw19d2aY1tn-eghqxM7FUHNW" title="Vegetables" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white', textDecoration: 'none'}}>vegetables</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}> used in this cuisine include, <u /><u /></span></p>
            <ul style={{marginTop: '0cm'}} type="disc">
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Cassava <u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Kangkong<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Spinach<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><span className="m_SpellE"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Genjer</span></b></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}><u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Papaya<u /><u /></span></b></li>
            </ul>
            <p className="MsoNormal" style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '18.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>Other vegetables
                include, </span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#548dd4', background: 'white'}}><u /><u /></span></b></p>
            <ul style={{marginTop: '0cm'}} type="disc">
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Eggplant<span> 
                    </span><u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Calabash<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Chayote<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><span className="m_SpellE"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Kelor</span></b></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}><u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><span className="m_SpellE"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Yardlong</span></b></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}> bean<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Gambas <u /><u /></span></b></li>
            </ul>
            <p className="MsoNormal" style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '18.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>are also used in
                different cuisines of Indonesia</span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>.</span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#548dd4', background: 'white'}}><u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><u><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>HERBS AND SEASONING</span></u><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>:<u /><u /></span></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '0cm', lineHeight: 'normal', background: 'white'}}><span style={{fontSize: '12.0pt', fontFamily: '"Times New Roman",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Seasoning&source=gmail-html&ust=1638995755879000&usg=AOvVaw3bhEcvAG2zVVXfQDQFmdlB" title="Seasoning" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>Seasonings</span></a></span><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}> such as,<u /><u /></span></p>
            <ul style={{marginTop: '0cm'}} type="disc">
              <li className="MsoNormal" style={{color: '#548dd4', marginTop: '6.0pt', marginBottom: '6.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif'}}>Ginger<span> </span><u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginTop: '6.0pt', marginBottom: '6.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif'}}>Nutmeg<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginTop: '6.0pt', marginBottom: '6.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif'}}>Clove<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginTop: '6.0pt', marginBottom: '6.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif'}}>Pandan leaves<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginTop: '6.0pt', marginBottom: '6.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif'}}>Black pepper<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginTop: '6.0pt', marginBottom: '6.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif'}}>Turmeric <u /><u /></span></b></li>
            </ul>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '18.0pt', lineHeight: 'normal', background: 'white'}}><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>, are widely used in many regional cuisines. </span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}><u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '0cm', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Sauces include <u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '72.0pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#a78470'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Soy sauce<u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '72.0pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#a78470'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Peanut
                  sauce<u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '72.0pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#a78470'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Coconut
                  milk <u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', textIndent: '36.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>,</span></b><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}> </span></b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>are also widely used. </span><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}><u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><u><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%', fontFamily: '"Cambria",serif'}}>DESERT AND SNACKS:<u /><u /></span></u></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>Indonesia has a rich collection of
                snacks called <span className="m_SpellE"><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Kue&source=gmail-html&ust=1638995755879000&usg=AOvVaw0_49c9xomG8J0euUI77Arj" title="Kue" target="_blank" rel="noreferrer"><span style={{color: '#0645ad', textDecoration: 'none'}}>kue</span></a></span> (cakes and
                pastry), both savoury and sweet.<u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>Traditional crackers are called </span><span style={{lineHeight: '115%'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Krupuk&source=gmail-html&ust=1638995755879000&usg=AOvVaw2x9UKEfPXZ6TJv1id87bNQ" title="Krupuk" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#0645ad', background: 'white', textDecoration: 'none'}}>krupuk</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>, made from bits of shrimp, fish, vegetables or nuts, which are usually
                consumed as a crunchy snack or to accompany main meals.<u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>Many popular drinks are based on ice
                (es) and can also be classified as desserts. <u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><u><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%', fontFamily: '"Cambria",serif'}}>BEVERAGES:<u /><u /></span></u></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>The most common and popular Indonesian
                drinks and beverages are <span className="m_SpellE">teh</span> (</span><span style={{lineHeight: '115%'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Tea&source=gmail-html&ust=1638995755879000&usg=AOvVaw3J39dIir_9ricEH1MJeDHw" title="Tea" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#0645ad', background: 'white', textDecoration: 'none'}}>tea</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>) and kopi (</span><span style={{lineHeight: '115%'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Coffee&source=gmail-html&ust=1638995755879000&usg=AOvVaw2E5F3BgZlJN2JnTyTQQtCf" title="Coffee" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#0645ad', background: 'white', textDecoration: 'none'}}>coffee</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>).<u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>As a </span><span style={{lineHeight: '115%'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Muslim&source=gmail-html&ust=1638995755879000&usg=AOvVaw0N6NpvTPAQ_bEVnY0JiMqD" title="Muslim" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#0645ad', background: 'white', textDecoration: 'none'}}>Muslim</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>-majority country, Indonesian Muslims share </span><span style={{lineHeight: '115%'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Islamic_dietary_laws&source=gmail-html&ust=1638995755879000&usg=AOvVaw0IXuUEartsjQySOHuaBHFc" title="Islamic dietary laws" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#0645ad', background: 'white', textDecoration: 'none'}}>Islamic dietary laws</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}> that prohibit alcoholic beverages</span><span lang="EN-US" style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif'}}><u /><u /></span></p>
            <p className="MsoNormal"><u /> <u /></p>
          </div>
        </div>
      </div>
    );
}
export default IndoComp