function thaicomp()
{
    return(
        <div>
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" /><style dangerouslySetInnerHTML={{__html: "p.m_MsoNormal,li.m_MsoNormal,div.m_MsoNormal{margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:11.0pt;font-family:\"Calibri\",sans-serif}span.m_SpellE{}span.m_GramE{}.m_MsoChpDefault{font-family:\"Calibri\",sans-serif}.m_MsoPapDefault{margin-bottom:8.0pt;line-height:107%}@page WordSection1{margin:72.0pt 72.0pt 72.0pt 72.0pt}div.m_WordSection1{}ol{margin-bottom:0cm}ul{margin-bottom:0cm}" }} />
        <div bgcolor="#DFD7E7" lang="EN-IN" style={{wordWrap: 'break-word'}}>
          <div className="m_WordSection1">
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><b><u><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%', fontFamily: '"Cambria",serif'}}>THAI CUISINE<u /><u /></span></u></b></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>INTRODUCTION<u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>Traditional Thai cuisine loosely falls
                into four categories: tom (boiled dishes), yam (spicy
                salads), tam (pounded foods), and <span className="m_SpellE">gaeng</span> (curries).
                Deep-fries, stir-fries, and steamed dishes derive from Chinese cooking.<u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><u><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>STAPLE FOOD</span></u><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>:<u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>Chinese food staples are mainly </span><span style={{lineHeight: '115%'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Rice&source=gmail-html&ust=1638997369152000&usg=AOvVaw3OTFxuno4_UObtzjLCc0l2" title="Rice" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#548dd4', background: 'white', textDecoration: 'none'}}>rice</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#548dd4', background: 'white'}}>, </span></b><span style={{lineHeight: '115%'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Noodles&source=gmail-html&ust=1638997369152000&usg=AOvVaw38yme1VPo-1EgGdvSNQgYg" title="Noodles" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#548dd4', background: 'white', textDecoration: 'none'}}>noodles</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#548dd4', background: 'white'}}>, shrimp</span></b><span style={{lineHeight: '115%', fontFamily: '"Cambria",serif'}}>.<u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><u><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%', fontFamily: '"Cambria",serif'}}>VEGETABLES USED IN CHINESE CUISINE:<u /><u /></span></u></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>Apart from vegetables that can be
                commonly seen, some unique </span><span style={{lineHeight: '115%'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Vegetables&source=gmail-html&ust=1638997369152000&usg=AOvVaw2rLlMb55W8BC2ICONxeJYP" title="Vegetables" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white', textDecoration: 'none'}}>vegetables</span></a></span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}> used in Thai cuisine include, <u /><u /></span></p>
            <ul style={{marginTop: '0cm'}} type="disc">
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Broccoli <u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Eggplant<u /><u /></span></b></li>
            </ul>
            <p className="MsoNormal" style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '36.0pt', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#548dd4', background: 'white'}}><u /> <u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '18.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>Other vegetables
                include, </span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#548dd4', background: 'white'}}><u /><u /></span></b></p>
            <ul style={{marginTop: '0cm'}} type="disc">
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><span style={{lineHeight: '115%', color: 'windowtext'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Bean_sprout&source=gmail-html&ust=1638997369153000&usg=AOvVaw3Rw-mEkmU4Nq74brMtWNUd" title="Bean sprout" target="_blank" rel="noreferrer"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#548dd4', background: 'white', textDecoration: 'none'}}>Bean
                        sprouts</span></b></a></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}><u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><span className="m_SpellE"><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Yardlong</span></b></span><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}> beans<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Bamboo shoots<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Tomatoes<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Cucumber <u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Chinese kale<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Chinese cabbage<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginBottom: '0cm', marginTop: '0cm', lineHeight: '115%'}}><b><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', background: 'white'}}>Mushroom<u /><u /></span></b></li>
            </ul>
            <p className="MsoNormal" style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '18.0pt', lineHeight: '115%'}}><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>are also used in
                different cuisines of Thai</span><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: '#202122', background: 'white'}}>.<u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><u><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>HERBS AND SEASONING</span></u><span style={{fontSize: '10.5pt', lineHeight: '115%', fontFamily: '"Cambria",serif', color: 'black', background: 'white'}}>:<u /><u /></span></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '0cm', lineHeight: 'normal', background: 'white'}}><span style={{fontSize: '12.0pt', fontFamily: '"Times New Roman",serif', color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Seasoning&source=gmail-html&ust=1638997369153000&usg=AOvVaw2kpZXHlwGjTCBcZhlZFTly" title="Seasoning" target="_blank" rel="noreferrer"><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>Seasonings</span></a></span><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}> such as,<u /><u /></span></p>
            <ul style={{marginTop: '0cm'}} type="disc">
              <li className="MsoNormal" style={{color: '#548dd4', marginTop: '6.0pt', marginBottom: '6.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif'}}>Coriander<span></span><u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginTop: '6.0pt', marginBottom: '6.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif'}}>Kaffir lime leaves<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginTop: '6.0pt', marginBottom: '6.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif'}}>Galangal<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginTop: '6.0pt', marginBottom: '6.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif'}}>Lemongrass<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginTop: '6.0pt', marginBottom: '6.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif'}}>Thai basil<u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginTop: '6.0pt', marginBottom: '6.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif'}}>Cloves <u /><u /></span></b></li>
              <li className="MsoNormal" style={{color: '#548dd4', marginTop: '6.0pt', marginBottom: '6.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif'}}>Turmeric <u /><u /></span></b></li>
            </ul>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', textIndent: '36.0pt', lineHeight: 'normal', background: 'white'}}><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>, are widely used in many regional cuisines. <u /><u /></span></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '0cm', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Sauces include <u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '72.0pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Soy
                  sauces<u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '72.0pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Peanut sauce<u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '72.0pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Fish
                  sauce<u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '72.0pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Shrimp
                  sauce<u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '72.0pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Tai <span className="m_SpellE">pla</span><u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', textIndent: '36.0pt', lineHeight: 'normal', background: 'white'}}><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>,</span></b><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}> </span></b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>are also widely used. </span><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}><u /><u /></span></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', lineHeight: 'normal', background: 'white'}}><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}><u /> <u /></span></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '36.0pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Wingdings', color: 'black'}}><span>Ø<span style={{font: '7.0pt "Times New Roman"'}}></span></span></span><u /><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: 'black'}}>Chillies also has a variety with different <span className="m_SpellE">flavors</span>: <u /><u /></span></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '53.45pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span className="m_SpellE"><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Phrik</span></b></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}> <span className="m_SpellE">khi</span> - Hottest chilli <u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '53.45pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span className="m_SpellE"><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Phrik</span></b></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}> <span className="m_SpellE">khi</span> nu  next hottest<u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '53.45pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span className="m_SpellE"><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Phirik</span></b></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}> chi fa  red or pink chillies<u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '53.45pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span className="m_SpellE"><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Phrik</span></b></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}> <span className="m_SpellE">yuak</span>  least <span className="m_GramE">spicy(</span>pale green)<u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginTop: '6.0pt', marginRight: '0cm', marginBottom: '6.0pt', marginLeft: '53.45pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.5pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span className="m_SpellE"><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Phrik</span></b></span><b><span style={{fontSize: '10.5pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}> <span className="m_SpellE">haeng</span>  dried chillies<u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><u><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%', fontFamily: '"Cambria",serif'}}><u /><span style={{textDecoration: 'none'}}> </span><u /></span></u></p>
            <p className="MsoNormal" style={{marginBottom: '10.0pt', lineHeight: '115%'}}><u><span lang="EN-US" style={{fontSize: '12.0pt', lineHeight: '115%', fontFamily: '"Cambria",serif'}}>DESERT AND SNACKS:<u /><u /></span></u></p>
            <p className="MsoNormal" style={{marginBottom: '1.2pt', marginLeft: '55.2pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.0pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Bua_loi&source=gmail-html&ust=1638997369153000&usg=AOvVaw2F-5kBerZgbwCiLxZB4kEO" title="Bua loi" target="_blank" rel="noreferrer"><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4', textDecoration: 'none'}}>Bua <span className="m_SpellE">loi</span></span></b></a></span><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}> </span></b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#0d0d0d'}}>
                mashed </span><span style={{color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Taro_root&source=gmail-html&ust=1638997369153000&usg=AOvVaw0bR5cOVEpi1kYwko7gln_5" title="Taro root" target="_blank" rel="noreferrer"><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#0d0d0d', textDecoration: 'none'}}>taro root</span></a></span><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#0d0d0d'}}> and </span><span style={{color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Pumpkin&source=gmail-html&ust=1638997369153000&usg=AOvVaw2eGIDSjAoGkiZG4HAyJEYk" title="Pumpkin" target="_blank" rel="noreferrer"><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#0d0d0d', textDecoration: 'none'}}>pumpkin</span></a></span><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#0d0d0d'}}> mixed
                with rice flour into small balls, boiled, then served in coconut milk.<u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '1.2pt', marginLeft: '55.2pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.0pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span className="m_SpellE"><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}>Chaokuai</span></b></span><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}> </span></b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#0d0d0d'}}> </span><span style={{color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Grass_jelly&source=gmail-html&ust=1638997369153000&usg=AOvVaw24ES8dO4v2_pDd1xZja8H8" title="Grass jelly" target="_blank" rel="noreferrer"><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#0d0d0d', textDecoration: 'none'}}>grass jelly</span></a></span><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#0d0d0d'}}> is
                often served with only shaved ice and </span><span style={{color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Brown_sugar&source=gmail-html&ust=1638997369153000&usg=AOvVaw0Bsb_VeTFQ_LQGlQDPFPyI" title="Brown sugar" target="_blank" rel="noreferrer"><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#0d0d0d', textDecoration: 'none'}}>brown sugar</span></a></span><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#0d0d0d'}}>.<u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '1.2pt', marginLeft: '55.2pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.0pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Chor_muang&source=gmail-html&ust=1638997369153000&usg=AOvVaw2aZVJkp6F_vm36kS3hSRVK" title="Chor muang" target="_blank" rel="noreferrer"><span className="m_SpellE"><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4', textDecoration: 'none'}}>Chor</span></b></span><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4', textDecoration: 'none'}}> <span className="m_SpellE">muang</span></span></b></a></span><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}><u /><u /></span></b></p>
            <p className="MsoNormal" style={{marginBottom: '1.2pt', marginLeft: '55.2pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.0pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Kanom_khrok&source=gmail-html&ust=1638997369153000&usg=AOvVaw07bKDxR0TuZMCMUUtB_d3S" title="Kanom khrok" target="_blank" rel="noreferrer"><span className="m_SpellE"><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4', textDecoration: 'none'}}>Kanom</span></b></span><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4', textDecoration: 'none'}}> <span className="m_SpellE">khrok</span></span></b></a></span><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#0d0d0d'}}> 
                coconut-rice pancakes, one of the ancient Thai desserts.<u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '1.2pt', marginLeft: '55.2pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.0pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Khanom_khrok_bai_toey&source=gmail-html&ust=1638997369153000&usg=AOvVaw1SheqqPcwNfegcBOq6Dz2g" title="Khanom khrok bai toey" target="_blank" rel="noreferrer"><span className="m_SpellE"><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4', textDecoration: 'none'}}>Khanom</span></b></span><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4', textDecoration: 'none'}}> <span className="m_SpellE">khrok</span>
                      bai toey</span></b></a></span><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}> </span></b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#0d0d0d'}}> ancient Thai dessert, shaped to
                look like flowers.<u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '1.2pt', marginLeft: '55.2pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.0pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><span style={{color: 'black'}}><a href="https://www.google.com/url?q=https://en.wikipedia.org/wiki/Khao_tom_mad&source=gmail-html&ust=1638997369153000&usg=AOvVaw1ta9dVPfZl1W_BKbBHQaq7" title="Khao tom mad" target="_blank" rel="noreferrer"><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4', textDecoration: 'none'}}>Khao tom mat</span></b></a></span><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#0d0d0d'}}> <span className="m_GramE"> <span style={{background: 'white'}}> a</span></span><span style={{background: 'white'}}>
                  traditional Thai dessert prepared from sticky rice, coconut milk, and banana.</span><u /><u /></span></p>
            <p className="MsoNormal" style={{marginBottom: '1.2pt', marginLeft: '55.2pt', lineHeight: 'normal', background: 'white'}}><u /><span style={{fontSize: '10.0pt', fontFamily: 'Symbol', color: '#848484'}}><span>·<span style={{font: '7.0pt "Times New Roman"'}}>       
                  </span></span></span><u /><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4', background: 'white'}}>Ice cream</span></b><b><span style={{fontSize: '12.0pt', fontFamily: '"Cambria",serif', color: '#548dd4'}}><u /><u /></span></b></p>
            <p className="MsoNormal"><u /> <u /></p>
          </div>
        </div>
      </div>
    );
}
export default thaicomp